//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public static class Utils
{

		public static bool ByteArrayCompare (byte[] a1, byte[] a2)
		{
				if (a1.Length != a2.Length)
						return false;

				for (int i=0; i<a1.Length; i++)
						if (a1 [i] != a2 [i])
								return false;

				return true;
		}
	
}


